getwd()
setwd("D:/Study&Learning/Coursera/DataScience")
outcome <- read.csv("week4assignment-outcome-of-care-measures.csv", header = TRUE, colClasses = "character") 
View(outcome)
head(outcome)
ncol(outcome)
nrow(outcome)
names(outcome)
outcome[, 11] <- as.numeric(outcome[, 11])
View(hist(outcome[, 11]))
colnames(outcome[11])
