setwd("C:\\All-Files\\Study&Learning\\Coursera\\DataScience")
source("rankall.R")
source("best.R")
source("rankhospital.R")

best("SC", "heart attack")
best("NY", "pneumonia")
best("AK", "pneumonia")
rankhospital("NC", "heart attack", "worst")
rankhospital("WA", "heart attack", 7)
rankhospital("TX", "pneumonia", 10)
rankhospital("NY", "heart attack", 7)
r <- rankall("heart attack", 4)
subset(r, r$State == "HI")
r <- rankall("pneumonia", "worst")
subset(r, r$State == "NJ")
r <- rankall("heart failure", 10) 
subset(r, r$State == "NV")
as.character(subset(r, state == "NV")$hospital)